# Generated by Django 4.2.7 on 2023-11-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_language_languagef'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languagef',
            new_name='Language',
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['english_name']},
        ),
    ]
